name: 'Update Resume'
description: 'Updates secure resume on website with google drive link'
inputs:
  file-url:
    description: 'Google drive link'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: .github/actions/update-resume

    - name: Get Resume
      id: get-resume
      run: node ${{ github.action_path }}/get.js
      shell: bash
      # env:
      #   FILE_URL: ${{ inputs.file-url }}

    - name: Encrypt Data
      id: encrypt-data
      run: node ${{ github.action_path }}/encrypt.js
      shell: bash
      env:
        RAW_DATA: ${{ steps.get-resume.outputs.raw-data }}

    - name: Raise PR
      id: raise-pr
      run: node ${{ github.action_path }}/raise.js
      shell: bash
      env:
        ENCRYPTED_DATA: ${{ steps.encrypt-data.outputs.encrypted-data }}