name: 'Update Resume'
description: 'Updates secure resume on website with google drive link'
inputs:
  file-url:
    description: 'Google drive link'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'index.js'