on: [workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to update the secure resume
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Resume
        uses: ./.github/actions/update-resume
        with:
          file-url: ${{ vars.FILE_URL }}
          resume-key: ${{ secrets.RESUME_KEY }}
          google-service-account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
