on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to update the secure resume
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Resume
        uses: ./.github/actions/update-resume
        with:
          file-url: ${{ vars.FILE_URL }}
          
