on: [push]

jobs:
  update-resume:
    runs-on: ubuntu-latest
    name: A job to update the secure resume
    steps:
      - uses: actions/checkout@v4
      - id: update-resume
        uses: ./.github/actions/update-resume
        with:
          file-url: ${{vars.FILE_URL}}
          
