on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: update-resume
        uses: ./.github/actions/update-resume
        with:
          file-url: ${{vars.FILE_URL}}
          
